const express = require('express');
const router = express.Router();
const dashboardRouter = require('./dashboard.route.js');
const homeRouter = require('./home.route.js');
const articlesRouter = require('./articles.route.js');
const contactRouter = require('./contact.route.js');
const authRouter =require('./auth.route.js');
router.use('/auth', authRouter);
router.use('/dashboard', dashboardRouter);
router.use('/home', homeRouter);
router.use('/articles', articlesRouter);
router.use('/contact', contactRouter);
module.exports = router;