const express = require('express');
const router = express.Router();
const loginRouter = require('./login.route.js');
const registerRouter = require('./register.route.js');
const dashboardRouter = require('./dashboard.route.js');
const homeRouter = require('./home.route.js');
const logoutRouter = require('./logout.route.js');
const articlesRouter = require('./articles.route.js');
router.use('/login', loginRouter);
router.use('/register', registerRouter);
router.use('/dashboard', dashboardRouter);
router.use('/logout', logoutRouter);
router.use('/home', homeRouter);
router.use('/articles', articlesRouter);
module.exports = router;